version: '3'
services:
  zoo1:
    image: zookeeper
    restart: always
    container_name: zoo1
    ports:
      - '2181:2181'
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  zoo2:
    image: zookeeper
    restart: always
    container_name: zoo2
    ports:
      - '2182:2181'
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  zoo3:
    image: zookeeper
    restart: always
    container_name: zoo3
    ports:
      - '2183:2181'
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
  zkui:
    image: zkui
    container_name: zkui
    ports:
      - '9090:9090'
    environment:
      - ZKUI_ZK_SERVER=zoo1:2181,zoo2:2181,zoo3:2181